---
abstract: 'A plugin for Log::Handler using Log::Hander::Output::DBI'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Handler-Plugin-DBI
provides:
  Log::Handler::Plugin::DBI:
    file: lib/Log/Handler/Plugin/DBI.pm
    version: 1.01
  Log::Handler::Plugin::DBI::CreateTable:
    file: lib/Log/Handler/Plugin/DBI/CreateTable.pm
    version: 1.01
requires:
  Carp: 1.2
  Config::Plugin::Tiny: 1
  DBD::SQLite: 1.35
  DBIx::Admin::CreateTable: 2.07
  DBIx::Connector: 0.47
  Hash::FieldHash: 0.12
  Log::Handler::Output::DBI: 0.11
  strict: 1.03
  vars: 1.01
  warnings: 1.03
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.01
